### ISSUE TITLE
Audio skipping | ECONNRESET and UND_ERR_SOCKET

### ISSUE THREAD

**Issue by sentientyeet** [LakhindarPal/discord-player-bot#155]
**Describe the bug**
Getting ECONNRESET and UND_ERR_SOCKET a bunch, songs end up skipping parts.

**To Reproduce**
Play music
= Songs skip/cut
check `docker logs [container]`

**Expected behavior**
Not skipping.

**Screenshots**
N/A

**Additional Information:**

- OS: Debian 12
- Docker: 27.3.1
- Image: lakhindarpal/discord-player-bot:latest
- discord.js: 14.16.3
- discord-player: 6.7.1
- nodejs: 20.17.0
- npm: 10.8.2

**Error log**
```
TypeError: terminated
    at Fetch.onAborted (/usr/app/node_modules/youtubei.js/node_modules/undici/lib/fetch/index.js:1939:49)
    at Fetch.emit (node:events:519:28)
    at Fetch.terminate (/usr/app/node_modules/youtubei.js/node_modules/undici/lib/fetch/index.js:94:10)
    at Object.onError (/usr/app/node_modules/youtubei.js/node_modules/undici/lib/fetch/index.js:2110:34)
    at Request.onError (/usr/app/node_modules/youtubei.js/node_modules/undici/lib/core/request.js:330:27)
    at errorRequest (/usr/app/node_modules/youtubei.js/node_modules/undici/lib/client.js:2276:13)
    at TLSSocket.onSocketClose (/usr/app/node_modules/youtubei.js/node_modules/undici/lib/client.js:1152:5)
    at TLSSocket.emit (node:events:531:35)
    at node:net:339:12
    at TCP.done (node:_tls_wrap:657:7) {
  [cause]: Error: read ECONNRESET
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:218:20)
      at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -104,
    code: 'ECONNRESET',
    syscall: 'read'
  }
}
TypeError: terminated
    at Fetch.onAborted (/usr/app/node_modules/youtubei.js/node_modules/undici/lib/fetch/index.js:1939:49)
    at Fetch.emit (node:events:519:28)
    at Fetch.terminate (/usr/app/node_modules/youtubei.js/node_modules/undici/lib/fetch/index.js:94:10)
    at Object.onError (/usr/app/node_modules/youtubei.js/node_modules/undici/lib/fetch/index.js:2110:34)
    at Request.onError (/usr/app/node_modules/youtubei.js/node_modules/undici/lib/core/request.js:330:27)
    at errorRequest (/usr/app/node_modules/youtubei.js/node_modules/undici/lib/client.js:2276:13)
    at TLSSocket.onSocketClose (/usr/app/node_modules/youtubei.js/node_modules/undici/lib/client.js:1152:5)
    at TLSSocket.emit (node:events:531:35)
    at node:net:339:12
    at TCP.done (node:_tls_wrap:657:7) {
  [cause]: SocketError: other side closed
      at TLSSocket.onSocketEnd (/usr/app/node_modules/youtubei.js/node_modules/undici/lib/client.js:1118:22)
      at TLSSocket.emit (node:events:531:35)
      at endReadableNT (node:internal/streams/readable:1696:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'UND_ERR_SOCKET',
    socket: {
      localAddress: '172.17.0.3',
      localPort: 40640,
      remoteAddress: undefined,
      remotePort: undefined,
      remoteFamily: undefined,
      timeout: undefined,
      bytesWritten: 1316,
      bytesRead: 3392477
    }
  }
}
```

**Comment by LakhindarPal** [comment]
Is it happening for SoundCloud songs also or just for youtube (Spotify,apple music) streaming?

**Comment by sentientyeet** [comment]
> Is it happening for SoundCloud songs also or just for youtube (Spotify,apple music) streaming?

Bot was being used with youtube songs specifically, no other service was tried.

**Comment by Minecatl1** [comment]
> **Describe the bug** Getting ECONNRESET and UND_ERR_SOCKET a bunch, songs end up skipping parts.
> 
> **To Reproduce** Steps to reproduce the behavior: Play music = Songs skip/cut check `docker logs [container]`
> 
> **Expected behavior** Not skipping.
> 
> **Screenshots** N/A
> 
> **Additional Information:**
> 
> * OS: Debian 12
> * Docker: 27.3.1
> * Image: lakhindarpal/discord-player-bot:latest
> * discord.js: 14.16.3
> * discord-player: 6.7.1
> * nodejs: 20.17.0
> * npm: 10.8.2
> 
> **Error log**
> 
> ```
> TypeError: terminated
>     at Fetch.onAborted (/usr/app/node_modules/youtubei.js/node_modules/undici/lib/fetch/index.js:1939:49)
>     at Fetch.emit (node:events:519:28)
>     at Fetch.terminate (/usr/app/node_modules/youtubei.js/node_modules/undici/lib/fetch/index.js:94:10)
>     at Object.onError (/usr/app/node_modules/youtubei.js/node_modules/undici/lib/fetch/index.js:2110:34)
>     at Request.onError (/usr/app/node_modules/youtubei.js/node_modules/undici/lib/core/request.js:330:27)
>     at errorRequest (/usr/app/node_modules/youtubei.js/node_modules/undici/lib/client.js:2276:13)
>     at TLSSocket.onSocketClose (/usr/app/node_modules/youtubei.js/node_modules/undici/lib/client.js:1152:5)
>     at TLSSocket.emit (node:events:531:35)
>     at node:net:339:12
>     at TCP.done (node:_tls_wrap:657:7) {
>   [cause]: Error: read ECONNRESET
>       at TLSWrap.onStreamRead (node:internal/stream_base_commons:218:20)
>       at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
>     errno: -104,
>     code: 'ECONNRESET',
>     syscall: 'read'
>   }
> }
> TypeError: terminated
>     at Fetch.onAborted (/usr/app/node_modules/youtubei.js/node_modules/undici/lib/fetch/index.js:1939:49)
>     at Fetch.emit (node:events:519:28)
>     at Fetch.terminate (/usr/app/node_modules/youtubei.js/node_modules/undici/lib/fetch/index.js:94:10)
>     at Object.onError (/usr/app/node_modules/youtubei.js/node_modules/undici/lib/fetch/index.js:2110:34)
>     at Request.onError (/usr/app/node_modules/youtubei.js/node_modules/undici/lib/core/request.js:330:27)
>     at errorRequest (/usr/app/node_modules/youtubei.js/node_modules/undici/lib/client.js:2276:13)
>     at TLSSocket.onSocketClose (/usr/app/node_modules/youtubei.js/node_modules/undici/lib/client.js:1152:5)
>     at TLSSocket.emit (node:events:531:35)
>     at node:net:339:12
>     at TCP.done (node:_tls_wrap:657:7) {
>   [cause]: SocketError: other side closed
>       at TLSSocket.onSocketEnd (/usr/app/node_modules/youtubei.js/node_modules/undici/lib/client.js:1118:22)
>       at TLSSocket.emit (node:events:531:35)
>       at endReadableNT (node:internal/streams/readable:1696:12)
>       at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
>     code: 'UND_ERR_SOCKET',
>     socket: {
>       localAddress: '172.17.0.3',
>       localPort: 40640,
>       remoteAddress: undefined,
>       remotePort: undefined,
>       remoteFamily: undefined,
>       timeout: undefined,
>       bytesWritten: 1316,
>       bytesRead: 3392477
>     }
>   }
> }
> ```

First update npm by running "npm update"

**Comment by Appilot-dev** [comment]
Andriod karma farming bot that runs on your device controlled from your dashboard.

We have made a reddit bot in 2024 but it functions through your phone remotely with a web dashboard no ADB or wire needed, a reddit karma bot that mimics human behavior through a learning script for the bot that shadows different humanized ways of managing an account of reddit.
You can check it's commenting features in [our repository](https://github.com/Appilot-dev/Reddit-Android-Karma-Farming-Bot)
How you can control the bot’s speed and never get banned again.
